[build-system]
requires = ["requests", "pytz"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "badgr_light"
author = "Glen Jarvis"
author-email = "glen@glenjarvis.com"
home-page = "https://github.com/glenjarvis/badgr-lite/"
description-file = "./README.md"
classifiers = ["License :: OSI Approved :: MIT License"]
requires-python = ">=3.3"
