# Python CircleCI 2.1 configuration file
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
             pipenv install
             pipenv check
             source /home/circleci/.local/share/virtualenvs/repo-eQF46Ow3/bin/activate
             echo "Testing Repo name: $CIRCLE_PR_REPONAME"

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

      - run:
          name: run tests
          command: |
            echo "hello world"

      #- store_artifacts:
      #    path: test-reports
      #    destination: test-reports
